import 'package:flutter_team_inggris/model/teamlist.dart';

var teamList = [
  Team(
    id: 57,
    areaId: 2072,
    areaName: 'England',
    name: 'Arsenal FC',
    shortName: 'Arsenal',
    tla: 'ARS',
    crestUrl: 'images/arsenal.png',
    address: "75 Drayton Park London N5 1BU",
    phone: "+44 (020) 76195003",
    website: "http://www.arsenal.com",
    email: "info@arsenal.co.uk",
    founded: 1886,
    clubColors: "Red / White",
    venue: "Emirates Stadium",
  ),
  Team(
    id: 58,
    areaId: 2072,
    areaName: "England",
    name: "Aston Villa FC",
    shortName: "Aston Villa",
    tla: "AST",
    crestUrl: "images/avfc.png",
    address: "Villa Park Birmingham B6 6HE",
    phone: "+44 (0121) 3272299",
    website: "http://www.avfc.co.uk",
    email: null,
    founded: 1872,
    clubColors: "Claret / Sky Blue",
    venue: "Villa Park",
  ),
  Team(
    id: 61,
    areaId: 2072,
    areaName: "England",
    name: "Chelsea FC",
    shortName: "Chelsea",
    tla: "CHE",
    crestUrl: "images/cfc.png",
    address: "Fulham Road London SW6 1HS",
    phone: "+44 (0871) 9841955",
    website: "http://www.chelseafc.com",
    email: null,
    founded: 1905,
    clubColors: "Royal Blue / White",
    venue: "Stamford Bridge",
  ),
  Team(
    id: 62,
    areaId: 2072,
    areaName: "England",
    name: "Everton FC",
    shortName: "Everton",
    tla: "EVE",
    crestUrl: "images/62.png",
    address: "Goodison Park Liverpool L4 4EL",
    phone: "+44 (0871) 6631878",
    website: "http://www.evertonfc.com",
    email: "everton@evertonfc.com",
    founded: 1878,
    clubColors: "Blue / White",
    venue: "Goodison Park",
  ),
  Team(
    id: 63,
    areaId: 2072,
    areaName: "England",
    name: "Fulham FC",
    shortName: "Fulham",
    tla: "FUL",
    crestUrl: "images/63.png",
    address: "Craven Cottage, Stevenage Road London SW6 6HH",
    phone: "+44 (0870) 4421222",
    website: "http://www.fulhamfc.com",
    email: "enquiries@fulhamfc.com",
    founded: 1879,
    clubColors: "White / Black",
    venue: "Craven Cottage",
  ),
  Team(
    id: 64,
    areaId: 2072,
    areaName: "England",
    name: "Liverpool FC",
    shortName: "Liverpool",
    tla: "LIV",
    crestUrl: "images/64.png",
    address: "Anfield Road Liverpool L4 0TH",
    phone: "+44 (0844) 4993000",
    website: "http://www.liverpoolfc.tv",
    email: "customercontact@liverpoolfc.tv",
    founded: 1892,
    clubColors: "Red / White",
    venue: "Anfield",
  ),
  Team(
    id: 65,
    areaId: 2072,
    areaName: "England",
    name: "Manchester City FC",
    shortName: "Man City",
    tla: "MCI",
    crestUrl: "images/65.png",
    address: "SportCity Manchester M11 3FF",
    phone: "+44 (0870) 0621894",
    website: "https://www.mancity.com",
    email: "mancity@mancity.com",
    founded: 1880,
    clubColors: "Sky Blue / White",
    venue: "Etihad Stadium",
  ),
  Team(
    id: 66,
    areaId: 2072,
    areaName: "England",
    name: "Manchester United FC",
    shortName: "Man United",
    tla: "MUN",
    crestUrl: "images/66.png",
    address: "Sir Matt Busby Way Manchester M16 0RA",
    phone: "+44 (0161) 8688000",
    website: "http://www.manutd.com",
    email: "enquiries@manutd.co.uk",
    founded: 1878,
    clubColors: "Red / White",
    venue: "Old Trafford",
  ),
  Team(
    id: 67,
    areaId: 2072,
    areaName: "England",
    name: "Newcastle United FC",
    shortName: "Newcastle",
    tla: "NEW",
    crestUrl: "images/67.png",
    address: "Sports Direct Arena Newcastle upon Tyne NE1 4ST",
    phone: null,
    website: "http://www.nufc.co.uk",
    email: "admin@nufc.co.uk",
    founded: 1881,
    clubColors: "Black / White",
    venue: "St. James' Park",
  ),
  Team(
    id: 73,
    areaId: 2072,
    areaName: "England",
    name: "Tottenham Hotspur FC",
    shortName: "Tottenham",
    tla: "TOT",
    crestUrl: "images/73.png",
    address: "Bill Nicholson Way, 748 High Road London N17 0AP",
    phone: "+44 (0844) 4995000",
    website: "http://www.tottenhamhotspur.com",
    email: "customer.care@tottenhamhotspur.com",
    founded: 1882,
    clubColors: "Navy Blue / White",
    venue: "Tottenham Hotspur Stadium",
  ),
  Team(
    id: 74,
    areaId: 2072,
    areaName: "England",
    name: "West Bromwich Albion FC",
    shortName: "West Brom",
    tla: "WBA",
    crestUrl: "images/74.png",
    address: "The Hawthorns West Bromwich B71 4LF",
    phone: null,
    website: "http://www.wba.co.uk",
    email: "enquiries@wbafc.co.uk",
    founded: 1879,
    clubColors: "White / Navy Blue",
    venue: "The Hawthorns",
  ),
  Team(
    id: 76,
    areaId: 2072,
    areaName: "England",
    name: "Wolverhampton Wanderers FC",
    shortName: "Wolverhampton",
    tla: "WOL",
    crestUrl: "images/76.png",
    address: "Waterloo Road Wolverhampton WV1 4QR",
    phone: "+44 (0871) 2222220",
    website: "http://www.wolves.co.uk",
    email: "info@wolves.co.uk",
    founded: 1877,
    clubColors: "Black / Gold",
    venue: "Molineux Stadium",
  ),
  Team(
    id: 328,
    areaId: 2072,
    areaName: "England",
    name: "Burnley FC",
    shortName: "Burnley",
    tla: "BUR",
    crestUrl: "images/328.png",
    address: "Harry Potts Way Burnley BB10 4BX",
    phone: "+44 (0871) 2211882",
    website: "http://www.burnleyfootballclub.com",
    email: "info@burnleyfc.com",
    founded: 1881,
    clubColors: "Claret / Sky Blue",
    venue: "Turf Moor",
  ),
  Team(
    id: 338,
    areaId: 2072,
    areaName: "England",
    name: "Leicester City FC",
    shortName: "Leicester City",
    tla: "LEI",
    crestUrl: "images/338.png",
    address: "The Walkers Stadium, Filbert Way Leicester LE2 7FL",
    phone: "+44 (0844) 8156000",
    website: "http://www.lcfc.com",
    email: null,
    founded: 1884,
    clubColors: "Royal Blue / White",
    venue: "King Power Stadium",
  ),
  Team(
    id: 340,
    areaId: 2072,
    areaName: "England",
    name: "Southampton FC",
    shortName: "Southampton",
    tla: "SOU",
    crestUrl: "images/340.png",
    address: "Britannia Road Southampton SO14 5FP",
    phone: null,
    website: "http://www.saintsfc.co.uk",
    email: "sfc@saintsfc.co.uk",
    founded: 1885,
    clubColors: "Red / White / Black",
    venue: "St. Mary's Stadium",
  ),
  Team(
    id: 341,
    areaId: 2072,
    areaName: "England",
    name: "Leeds United FC",
    shortName: "Leeds United",
    tla: "LEE",
    crestUrl: "images/341.png",
    address: "Elland Road Leeds LS11 0ES",
    phone: "+44 (0871) 3341919",
    website: "http://www.leedsunited.com",
    email: "reception@leedsunited.com",
    founded: 1904,
    clubColors: "White / Blue",
    venue: "Elland Road",
  ),
  Team(
    id: 354,
    areaId: 2072,
    areaName: "England",
    name: "Crystal Palace FC",
    shortName: "Crystal Palace",
    tla: "CRY",
    crestUrl: "images/354.png",
    address: "Whitehorse Lane London SE25 6PU",
    phone: "+44 (020) 87686000",
    website: "http://www.cpfc.co.uk",
    email: "info@cpfc.co.uk",
    founded: 1905,
    clubColors: "Red / Blue",
    venue: "Selhurst Park",
  ),
  Team(
    id: 356,
    areaId: 2072,
    areaName: "England",
    name: "Sheffield United FC",
    shortName: "Sheffield Utd",
    tla: "SHE",
    crestUrl: "images/356.png",
    address: "Bramall Lane Sheffield, Yorkshire S2 4SU",
    phone: "+44 (0871) 9951899",
    website: "http://www.sufc.co.uk",
    email: "info@sufc.co.uk",
    founded: null,
    clubColors: "Red / White / Black",
    venue: "Bramall Lane",
  ),
  Team(
    id: 397,
    areaId: 2072,
    areaName: "England",
    name: "Brighton & Hove Albion FC",
    shortName: "Brighton Hove",
    tla: "BHA",
    crestUrl: "images/397.png",
    address: "44 North Road Brighton & Hove BN1 1YR",
    phone: "+44 (01273) 878288",
    website: "http://www.seagulls.co.uk",
    email: "seagulls@bhafc.co.uk",
    founded: 1898,
    clubColors: "Blue / White",
    venue: "The American Express Community Stadium",
  ),
  Team(
    id: 563,
    areaId: 2072,
    areaName: "England",
    name: "West Ham United FC",
    shortName: "West Ham",
    tla: "WHU",
    crestUrl: "images/563.png",
    address: "Queen Elizabeth Olympic Park, London London E20 2ST",
    phone: "+44 (020) 85482794",
    website: "http://www.whufc.com",
    email: "yourcomments@westhamunited.co.uk",
    founded: 1895,
    clubColors: "Claret / Sky Blue",
    venue: "London Stadium",
  )
];

